title: Advanced Calculus MATH20471
author: Jonathan Crofts
copyright: 2021
logo: content/images/math.png

sphinx:
  config:
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

latex:
  latex_documents:
    targetname: book.tex

parse:
  myst_enable_extensions:
    - amsmath

repository: 
  url: https://github.com/jjcrofts77/Advanced-Calculus-MATH20471
html:
  use_repository_button: true
